name: Build and Test C Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install -y build-essential
      - run: make clean all
      - run: make test

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: choco install mingw -y
      - run: make clean all
      - run: test\run.exe
